name: WitherShot
description: WitherShot is a Bukkit plugin designed to let you shoot wither skulls from a bow.
author: jflory7
website: http://dev.bukkit.org/bukkit-plugins/withershot/
main: com.justinwflory.withershot.Main
version: 0.2

commands:
    withershot:
        description: Allows/disallows a player to shoot wither skulls.
        usage: /withershot <enable, disable>
        permission: withershot.fire
        permission-message: You do not have the permission to use <permission>
        
permissions:
    withershot.fire:
        description: Allows/disallows a player to shoot wither skulls.
        default: op