name: WitherShot
description: WitherShot is a Bukkit plugin designed to let you shoot wither skulls from a bow.
author: jflory7
website: http://dev.bukkit.org/bukkit-plugins/withershot/
main: com.justinwflory.withershot.Main
version: ${version}

commands:
    ws:
        description: Allows / disallows a player to shoot wither skulls
        usage: /ws <enable, disable, reset>
        permission: withershot.fire
        permission-message: You do not have the permission to use <permission>
        aliases: [withershot, bow]

permissions:
    withershot.fire:
        description: Allows / disallows a player to shoot wither skulls
        default: op
    withershot.reset:
        description: Resets the players who have WitherShot enabled
        default: op