name: WitherBow
description: WitherBow is a Bukkit plugin designed to let you shoot wither skulls from a bow.
author: jflory7
main: com.crystalcraftmc.witherbow.Main
version: 0.1b

commands:
    witherbow:
        description: Allows/disallows a player to shoot wither skulls.
        usage: /witherbow <enable, disable>
        permission: witherbow.fire
        permission-message: You do not have permission to use <permission>

permissions:
    witherbow.fire:
        description: Allow a player to shoot wither skulls.
        default: op